FROM bitnami/spark:3

USER root
RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.231/aws-java-sdk-bundle-1.12.231.jar --output /opt/bitnami/spark/jars/aws-java-sdk-bundle-1.12.231.jar
RUN curl https://repo1.maven.org/maven2/net/java/dev/jets3t/jets3t/0.9.4/jets3t-0.9.4.jar --output /opt/bitnami/spark/jars/jets3t-0.9.4.jar

COPY ./dags/sparksql.py /opt/bitnami/spark
COPY fakefriends.csv /opt/bitnami/spark

COPY ./spark_requirements.txt /
RUN pip install -r /spark_requirements.txt